package cz.promptly.shared.enums;

public enum UserPermissionsEnum {
    AUTH_TOTP_READ,
    AUTH_TOTP_CREATE,
    AUTH_TOTP_DELETE,

    APP_SETTINGS_READ,
    APP_SETTINGS_UPDATE,

    USERS_READ,
    USERS_CREATE,
    USERS_UPDATE,
    USERS_DELETE,

    SENDERS_READ,
    SENDERS_CREATE,
    SENDERS_UPDATE,
    SENDERS_DELETE,

    CLIENTS_READ,
    CLIENTS_CREATE,
    CLIENTS_UPDATE,
    CLIENTS_DELETE,

    CLIENT_TOKENS_READ,
    CLIENT_TOKENS_CREATE,
    CLIENT_TOKENS_DELETE,

    TEMPLATES_READ,
    TEMPLATES_CREATE,
    TEMPLATES_UPDATE,
    TEMPLATES_DELETE,

    EMAILS_READ,

    EMAILS_CREATE;
}
